settings:
<<<<<<< HEAD
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200
=======
  title: "STH Status Page"
  url: "https://status-page.safethishome.workers.dev/" # used for Slack & Discord messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: "All Systems Operational"
  notAllmonitorsOperational: "Most Systems Operational"
  monitorLabelOperational: "Primary Systems Operational"
  monitorLabelNotOperational: "Systems Not Operational"
  monitorLabelNoData: "No data"
  dayInHistogramNoData: "No data"
  dayInHistogramOperational: "All systems checks good"
  dayInHistogramNotOperational: "Some checks failed"

# list of monitors
monitors:
  - id: safe-this-home # unique identifier
    name: SafeThisHome Primary Domain
    description: "Safe This Home » Cyber Security | Cloud Encryption | Data Protection" # default=empty
    url: "https://safethishome.com/" # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true
>>>>>>> Create STHCoders repo
