settings:
  title: "STH Status Page"
  url: "https://status.safethishome.workers.dev/" # used for Slack & Discord messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: "All Systems Operational"
  notAllmonitorsOperational: "Most Systems Operational (We are working to rectify the intermittent glitches.)"
  monitorLabelOperational: "All Primary Systems Online (Intermittent glitches have been observed, but all critical parts of the network are functioning properly.)"
  monitorLabelNotOperational: "Many Systems Not Operational (We are aware of the situation and working to ensure service is restored as quickly as possible.)"
  monitorLabelNoData: "Additional data is currently unavailable."
  dayInHistogramNoData: "Additional data is currently unavailable."
  dayInHistogramOperational: "All Systems Operational"
  dayInHistogramNotOperational: "Some checks are failing. (Troubleshooting is in progress as we speak.)"

# list of monitors
monitors:
  - id: safe-this-home # unique identifier
    name: Main Webpage (safethishome.com)
    description: "Safe This Home » Cyber Security | Cloud Encryption | Data Protection" # default=empty
    url: "https://safethishome.com/" # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true

  - id: sth-cyberblade # unique identifier
    name: The CyberBlade (newsletter.safethishome.com)
    description: "A relevant newsletter with valuable insights on the cybersecurity and user privacy crisis we are currently facing."
    url: "https://newsletter.safethishome.com/" # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true

  - id: sth-links # unique identifier
    name: Resharable Links (safethis.link)
    description: "A network of custom links that support the flow of relevant, sharable information from Safe This Home and our partners and brands." # default=empty
    url: "https://safethis.link/tuk/" # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true
