name = "sth-status-page"
workers_dev = false
account_id = "process.env.CF_WORKERS_ACCOUNT_ID"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["5 * * * *"]

[site]
bucket = "out"
entry-point = "./"
